# --- Notes --- 
# + No UI, yaml edit only: 
# + + If you use this preset file the UI editor will not be available
# -------------
- alias: Dishawasher - ASM
  id: f6e89034-b3e6-4951-9cea-7d7053b30857 # This id must be unique or an error will be thrown! Need help? Use this https://www.uuidgenerator.net/version1
  description: "[NO UI] Appliance State Monitor Automation - Control the state of the appliance using the power consumption values"
  use_blueprint:
    # Make sure you imported the blueprint before using this file.
    path: leofabri/appliance-status-monitor.yaml
    input:
      #########################################################################
      # Arbitrary variables | Change these according to your needs IMPORTANT! #
      #########################################################################
      # * Socket info
      appliance_socket: switch.dishwasher_outlet
      appliance_power_sensor: sensor.dishwasher_power

      # * Overload controls
      appliance_overload_state_enabled: false # false = disabled. Important! If you enable option, please also set the appliance_suspended_sensor below
      # appliance_suspended_sensor: input_number.potenza_1_sospesa # Overload indicator. You'll need a separate automation to detect overloads for this to work

      # * Timing
      delayed_job_ongoing_duration: 50 # seconds
      delayed_job_completion_duration: 140 # seconds
      job_completed_persistence_duration: 150 # seconds

      # * Power Thresholds
      # Don't know how to find the right power thresholds? Read the guide: <link>
      appliance_starting_power_threshold: 5 # Watts
      appliance_finishing_power_threshold: 2 # Watts

      # * Extras
      # appliance_job_completed_when_socket_is_off: true # default is false (disabled)

      # _____________________ #

      ###########
      # Helpers #
      ###########

      # These match the enties created in the packages/ folder
      # They are already matching the names, unless you changed them.
      automation_self_trigger: input_boolean.dishwasher_automation_self_trigger
      appliance_state_machine: input_select.dishwasher_state_machine
      appliance_job_cycle: input_boolean.dishwasher_job_cycle
      delayed_job_completion_timer: timer.dishwasher_delayed_job_completion_timer
      delayed_job_ongoing_timer: timer.dishwasher_delayed_job_ongoing_timer
      job_completed_persistence_timer: timer.dishwasher_job_completed_persistence_timer
